openapi: 3.0.0
components:
  schemas:
    ErrorResponse:
      title: Error Schema
      type: object
      properties:
        message:
          type: string
    CreateLogRequest:
      type: object
      properties:
        audit:
          type: object
          properties:
            items:
              type: array
              items:
                type: object
                properties:
                  created:
                    type: string
                  userId:
                    type: string
                  action:
                    type: string
                  url:
                    type: string
                  payload:
                    type: object
                    properties:
                      itemId:
                        type: string
                      amount:
                        type: integer
                    required:
                      - itemId
                      - amount
                required:
                  - created
                  - userId
                  - action
                  - url
              default: []
          required:
            - items
      required:
        - audit
    CreateLogResponse:
      type: object
      properties:
        audit:
          type: object
          properties:
            items:
              type: array
              items:
                type: object
                properties:
                  created:
                    type: string
                  userId:
                    type: string
                  action:
                    type: string
                  url:
                    type: string
                  payload:
                    type: object
                    properties:
                      itemId:
                        type: string
                      amount:
                        type: integer
                    required:
                      - itemId
                      - amount
                required:
                  - created
                  - userId
                  - action
                  - url
              default: []
          required:
            - items
      required:
        - audit
  securitySchemes: {}
info:
  title: Log Service API
  description: APIs for storing and retrieving logs
  version: '1'
paths:
  /log:
    post:
      operationId: log
      summary: Create Log
      description: Creates a log entry
      responses:
        '201':
          description: Log entry has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateLogResponse'
        '500':
          description: An error occurred while processing request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
